#! /bin/sh

bspc config border_width        3
bspc config window_gap          15

bspc config split_ratio         0.50
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_by_distance   true

bspc config top_padding         40
bspc config normal_border_color "#1C1C1C"
bspc config focused_border_color "#CE9B4E"

bspc monitor -d 1 2 3 4 5 6 7 8 9

bspc rule -a Gimp desktop=^5 follow=on floating=on
bspc rule -a Firefox desktop=^3 follow=on
bspc rule -a mplayer2 floating=on
bspc rule -a Skype desktop=^4 follow=on

